development:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  spotify_client_id: <%= Figaro.env.spotify_client_id %>
  spotify_client_secret: <%= Figaro.env.spotify_client_secret %>
  facebook_app_id: <%= Figaro.env.facebook_app_id %>
  facebook_app_secret: <%= Figaro.env.facebook_app_secret %>
  google_client_id: <%= Figaro.env.google_client_id %>
  google_client_secret: <%= Figaro.env.google_client_secret %>

test:
  secret_key_base: <%= Figaro.env.secret_key_base %>

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  spotify_client_id: <%= Figaro.env.spotify_client_id %>
  spotify_client_secret: <%= Figaro.env.spotify_client_secret %>
  facebook_app_id: <%= Figaro.env.facebook_app_id %>
  facebook_app_secret: <%= Figaro.env.facebook_app_secret %>
  google_client_id: <%= Figaro.env.google_client_id %>
  google_client_secret: <%= Figaro.env.google_client_secret %>